/**
 * Trust inside one school: what owners and staff can and can't do to each other.
 *
 * isolation.test.ts covers School A vs School B. This file covers the rules
 * within a school:
 *   1. A school always keeps at least one owner.
 *   2. Join codes are generated by the database; nobody can choose one.
 *   3. Records say who really did something: created_by and reviewed_by are
 *      always the signed-in user, never a colleague.
 *   4. Nobody adds members directly. Membership comes only from creating a
 *      school or accepting an invite sent to your email.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { CODE_ALPHABET, JOIN_CODE_LENGTH } from "@/lib/domain/codes";
import { seedTwoSchools, type TwoSchools } from "./fixtures";
import { openTestDb, TEST_SLUG_PREFIX, type TestDb } from "./harness";

const RLS_DENIED = /row-level security/i;
const NO_PRIVILEGE = /permission denied/i;
// Built from the TypeScript alphabet, so the database and the app can't drift apart.
const JOIN_CODE = new RegExp(`^[${CODE_ALPHABET}]{${JOIN_CODE_LENGTH}}$`);

let db: TestDb;
let s: TwoSchools;

beforeAll(async () => {
  db = await openTestDb();
  s = await seedTwoSchools(db);
}, 60_000);

afterAll(async () => {
  await db?.close();
});

describe(`school roles (${process.env.TEST_DB ?? "pglite"})`, () => {
  describe("1. a school always keeps an owner", () => {
    it("the only owner can't remove themselves", async () => {
      await expect(
        db.asUser(s.a.ownerId, (q) => q("delete from public.school_members where school_id = $1 and user_id = $2", [s.a.id, s.a.ownerId])),
      ).rejects.toThrow(/at least one owner/);
    });

    it("an owner can still remove staff", async () => {
      await db.asUser(s.a.ownerId, async (q) => {
        const rows = await q("delete from public.school_members where school_id = $1 and user_id = $2 returning user_id", [
          s.a.id,
          s.a.staffId,
        ]);
        expect(rows).toHaveLength(1);
      });
    });

    it("with two owners, one can remove the other, but not both at once", async () => {
      await db.asUser(s.b.ownerId, async (q) => {
        const rows = await q("delete from public.school_members where school_id = $1 and user_id = $2 returning user_id", [
          s.b.id,
          s.b.coOwnerId,
        ]);
        expect(rows).toHaveLength(1);
      });
      await expect(
        db.asUser(s.b.ownerId, (q) => q("delete from public.school_members where school_id = $1 and role = 'owner'", [s.b.id])),
      ).rejects.toThrow(/at least one owner/);
    });

    it("deleting a whole school still works (its members go with it)", async () => {
      const [school] = await db.owner(
        `insert into public.schools (slug, name, join_code) values ($1, 'Doomed School', public.generate_join_code()) returning id`,
        [`${TEST_SLUG_PREFIX}${db.runId}-doomed`],
      );
      await db.owner("insert into public.school_members (school_id, user_id, role) values ($1, $2, 'owner')", [school.id, s.a.ownerId]);
      await db.owner("delete from public.schools where id = $1", [school.id]);
      expect(await db.owner("select 1 from public.school_members where school_id = $1", [school.id])).toHaveLength(0);
    });
  });

  describe("2. join codes come only from the database", () => {
    it("an owner can't set the join code directly", async () => {
      await expect(
        db.asUser(s.a.ownerId, (q) => q("update public.schools set join_code = 'AAAAAAAA' where id = $1", [s.a.id])),
      ).rejects.toThrow(NO_PRIVILEGE);
    });

    it("create_school generates the code; the caller can't pass one", async () => {
      await db.asUser(s.a.ownerId, async (q) => {
        const [{ id }] = await q("select public.create_school($1, 'Code School', null, 'UTC', null, false) as id", [
          `${TEST_SLUG_PREFIX}${db.runId}-code`,
        ]);
        const [school] = await q("select join_code from public.schools where id = $1", [id]);
        expect(school.join_code).toMatch(JOIN_CODE);
      });
    });

    it("an owner can rotate the code, and the rotation is logged", async () => {
      await db.asUser(s.a.ownerId, async (q) => {
        const [before] = await q("select join_code from public.schools where id = $1", [s.a.id]);
        const [{ code }] = await q("select public.rotate_join_code($1) as code", [s.a.id]);
        expect(code).toMatch(JOIN_CODE);
        expect(code).not.toBe(before.join_code);
        const [after] = await q("select join_code from public.schools where id = $1", [s.a.id]);
        expect(after.join_code).toBe(code);
        const log = await q("select actor_id from public.audit_log where school_id = $1 and action = 'join_code.rotated'", [s.a.id]);
        expect(log.map((r) => r.actor_id)).toEqual([s.a.ownerId]);
      });
    });

    it("staff (not owners) can't rotate the code", async () => {
      await expect(db.asUser(s.a.staffId, (q) => q("select public.rotate_join_code($1)", [s.a.id]))).rejects.toThrow(/only an owner/);
    });

    it("nobody signed in can call the generator itself", async () => {
      await expect(db.asUser(s.a.ownerId, (q) => q("select public.generate_join_code()"))).rejects.toThrow(NO_PRIVILEGE);
    });

    it("generated codes use the whole alphabet, with no repeats in 2,000 draws", async () => {
      const rows = await db.owner("select public.generate_join_code() as code from generate_series(1, 2000)");
      const codes = rows.map((r) => r.code as string);
      for (const code of codes) expect(code).toMatch(JOIN_CODE);
      expect(new Set(codes).size).toBe(codes.length);
      expect(new Set(codes.join("")).size).toBe(CODE_ALPHABET.length);
    });
  });

  describe("3. records say who really did it", () => {
    it("a new item is recorded as created by whoever added it", async () => {
      await db.asUser(s.a.staffId, async (q) => {
        const [item] = await q(
          "insert into public.items (school_id, category, found_location_id, visibility) values ($1, 'keys', $2, 'limited') returning created_by",
          [s.a.id, s.a.locationId],
        );
        expect(item.created_by).toBe(s.a.staffId);
      });
    });

    it("staff can't add an item in a colleague's name", async () => {
      await expect(
        db.asUser(s.a.staffId, (q) =>
          q("insert into public.items (school_id, category, found_location_id, visibility, created_by) values ($1, 'keys', $2, 'limited', $3)", [
            s.a.id,
            s.a.locationId,
            s.a.ownerId,
          ]),
        ),
      ).rejects.toThrow(RLS_DENIED);
    });

    it("an owner can't send an invite in someone else's name", async () => {
      await db.asUser(s.a.ownerId, async (q) => {
        const [invite] = await q(
          "insert into public.staff_invites (school_id, email, token_hash) values ($1, 'new@example.com', $2) returning created_by",
          [s.a.id, `own-${db.runId}`],
        );
        expect(invite.created_by).toBe(s.a.ownerId);
      });
      await expect(
        db.asUser(s.a.ownerId, (q) =>
          q("insert into public.staff_invites (school_id, email, token_hash, created_by) values ($1, 'new@example.com', $2, $3)", [
            s.a.id,
            `forged-${db.runId}`,
            s.a.staffId,
          ]),
        ),
      ).rejects.toThrow(RLS_DENIED);
    });

    it("invites can't be edited after sending (revoke and resend instead)", async () => {
      await expect(
        db.asUser(s.a.ownerId, (q) => q("update public.staff_invites set email = 'x@example.com' where id = $1", [s.a.inviteId])),
      ).rejects.toThrow(NO_PRIVILEGE);
    });

    it("approving a claim records the signed-in reviewer and time; nobody can set them by hand", async () => {
      await db.asUser(s.a.staffId, async (q) => {
        const [claim] = await q("update public.claims set status = 'approved' where id = $1 returning reviewed_by, reviewed_at", [
          s.a.claimId,
        ]);
        expect(claim.reviewed_by).toBe(s.a.staffId);
        expect(claim.reviewed_at).not.toBeNull();
        const [pickedUp] = await q("update public.claims set status = 'picked_up' where id = $1 returning reviewed_by, picked_up_at", [
          s.a.claimId,
        ]);
        expect(pickedUp.reviewed_by).toBe(s.a.staffId);
        expect(pickedUp.picked_up_at).not.toBeNull();
      });
      await expect(
        db.asUser(s.a.staffId, (q) => q("update public.claims set reviewed_by = $1 where id = $2", [s.a.ownerId, s.a.claimId])),
      ).rejects.toThrow(NO_PRIVILEGE);
    });
  });

  describe("4. members only join by creating a school or accepting an invite", () => {
    it("an owner can't add a member directly, even to their own school", async () => {
      await expect(
        db.asUser(s.b.ownerId, (q) => q("insert into public.school_members (school_id, user_id, role) values ($1, $2, 'staff')", [s.b.id, s.a.ownerId])),
      ).rejects.toThrow(NO_PRIVILEGE);
    });

    it("the person an invite was sent to can accept it and becomes staff", async () => {
      const invitee = await db.createUser(`${TEST_SLUG_PREFIX}${db.runId}-a-invitee@example.com`);
      await db.asUser(invitee, async (q) => {
        const [row] = await q("select public.accept_staff_invite($1) as school_id", [`invite-${db.runId}-a`]);
        expect(row.school_id).toBe(s.a.id);
        const [member] = await q("select role from public.school_members where school_id = $1 and user_id = $2", [s.a.id, invitee]);
        expect(member.role).toBe("staff");
      });
    });
  });
});
